### ISSUE TITLE
Unique Session

### ISSUE THREAD

**Issue by modellhr** [farhadi/node-smpp#163] opened 2021-02-09 11:12 UTC
Hello @juliangut ,
hope you will be doing fine.

In my application, i am binding with multiple SMSC and storing sessions on redis with hostname and port. So in case if there is any thing wrong in connection, i get the SMSC id (id is generated in DB for specific SMSC) by host and port obtained from session object. And in this way i used to delete the session from redis.
This approach is working fine in case i have to bind with single username and pwd. But in case if any one of SMSC provide more than one username and pwd (to bind with same system_id and port), then is there a way to get some key that is unique in each session object?  like any session id for example? so that i could decide with session object, which session has issue.

**Comment by juliangut** [comment] 2021-02-09 11:55
Hi @modellhr 

I'm sorry but I do not get your distinction between username and system_id

As an option, instead of identifying each SMSC by host/port I'd use system_id instead. You could give the session a custom identifier based on your own logic, and match it in your store

```js
session.on('bind_transceiver', function (pdu) {
  // [...]
  session.identifier = getCustomIdentifier(session, pdu, smscConfig, ...);
  // [...]
}
```

**Comment by modellhr** [comment] 2021-02-09 12:15
Sorry for confusion. Both username and system_id are same.

Ok so we can add identifier key with some value in session object?

**Comment by fardhana** [comment] 2021-04-07 15:41
Hi, Can we store the session in external data store like redis?
I want to running node-smpp in pm2 cluster mode, but seems like the session only available on single process.

If it possible to store the session into redis, then i can store it them and use it when send the delivery_sm, because in my case DR is triggered by webhook (my provider send the DR via webhook / push DR)

The problem is, i cannot find how to store the smpp session into redis.

**Comment by anildalar** [comment] 2021-04-07 16:22
We can help to store the session in redis.
We have successfully completed smpp and redis Intrigration on OKMESSEGING
System. https://oklabs.in

**Comment by juliangut** [comment] 2021-04-19 11:19
Storing the session id in redis or any other data store is out of the scope of this library

As mentioned before you can create a session identifier based in your own logic, that will always be the same given the same data (system_id, IP, client data from ddbb, etc), and then use that to identify your connections

Once you have that unique identifier you can use it to connect to a different queue per client or IP or you name it, to find what PDUs need to be sent, either submit_sm or deliver_sm depending on what side of the connection you are and the bind mode used

**Comment by anildalar** [comment] 2021-04-19 13:12
We have successfully developed a smpp plateform using node-smpp , Kafka and
redis. If any one need professional service. We can help.
Thanks & Regards.
https://oklabs.in
OKMESSAGING
AnilDollor

**Comment by juliangut** [comment] 2021-04-19 14:26
@anildalar I'd appreciate if you could stop spamming this issue or any other

You could advertise yourself or your company directly to the developer instead of doing it publicly, IMHO github's issues are not the place for this

Please stop

**Comment by augustolzd** [comment] 2021-05-08 21:59
I was struggling a bit with the library and I can't find the way how to use a unique session ID, I'm using your library some time ago. I use my own auth method to connect but my connection is permanent because we need to send constantly many requests but I can't know which user is using the connection, maybe someone already solves how to handle this. I appreciate any advice :D

**Comment by juliangut** [comment] 2021-05-20 09:38
I'm closing this issue as I think the matter of unique session ids has already been explained. Feel free to reopen if more information is needed

**Closed by juliangut** 2021-05-20 09:38 UTC
