### ISSUE TITLE
Sending DLR in case multiple clients binded

### ISSUE THREAD

**Issue by modellhr** [farhadi/node-smpp#130] opened 2020-04-24 06:46 UTC
Hello,

How to make sure that DLR is sent to client with whom it belongs to?
Normally when DLR received here is how i am sending it back to client.

`session.on('pdu', function(pdu){
  if(pdu.command === 'deliver_sm'){
   session.send(new smpp.PDU('deliver_sm', {
    esm_class: 4,
    short_message: pdu.short_message.message,
    source_addr: pdu.source_addr,
    destination_addr: pdu.destination_addr,
    receipted_message_id: client.id
}));
}
})`

Thanks,

**Comment by juliangut** [comment] 2020-05-18 14:59
If you're acting as a middleware (or proxy) between you clients and your providers you have to keep track of every message received and each PDU sent for those messages

The simplest way in when you make `session.send()` you can specify a response callback in which you can wait for the response PDU, directly there you a can send the response PDU to your client

A more complex solution would be to save received messages alongside provider's submit_sm_resp message_ids, so that when you receive deliver_sm for a message_id you can send it back to the corresponding client

**Comment by modellhr** [comment] 2020-05-19 07:23
In my case yes it is acting as a middleware.  DLRs are storing in messaging queue and from there server is consuming and sending. I saved the message_id along with user IP when submit_sm request initiated and upon receiving DLR, matching with ID and then getting the right user. So just wanted to know if session.send() will emit the broadcast to all of its connected clients? Or is there a way to send specifically to one client (based on IP or Port)

**Comment by modellhr** [comment] 2020-07-06 13:59
@juliangut ^^

**Comment by juliangut** [comment] 2020-07-06 14:14
Hi modellhr

`session.send()` will send the PDU to the client connected to that session in particular, remember each client connects and binds to a session

If you match each session with the messages received through it you can then send the DLR over that single session, anyway remember client can do a receiver bind only, meaning they only expect to receive DLRs over that bind, that said I'd send the DLR only once over any of the transceiver and receiver binds for a single user

**Comment by modellhr** [comment] 2020-07-09 09:14
Thanks juliangut,
So basically, in this case we could have two points where we can store client session.
(1)  `session.on("bind_transceiver", ...) // Store the session along with user detail. this point is useful in case if client only binds as receiver as you mentioned earlier.`
(2) ```
session.on("submit_sm", async pdu => {
      let message_id = uuid();
      sessions_array.push({message_id, session}) // storage place for sessions
}) 
```

and when `DLR `comes, match the `message_id` in the sessions storage (in this case , an array), get the session object and send the `DLR` back over that session. So this approach is right?

**Comment by juliangut** [comment] 2020-07-29 20:43
In the end I would not try to look too hard on the session id, because your client could close the connection and reconnect back, in that case the session id would change and you wouldn't be able to send the DLR back to him

What I'd do instead is
* Every time your client sends a message store it with your client_id (in a ddbb or whatever)
* Store the message_id you received from your provider when sending the message and assign it to your client id
* When you receive the DLR from the provider it has the message_id, so you look for that message_id in your store and you know which client to sent it to

I don't recommend you to blindly proxy submit_sm and deliver_sm, but develop your solution in the mmiddle to handle communication from/to your client and to/from your provider

**Comment by juliangut** [comment] 2020-10-03 14:25
Closing as it feels like the issue is resolved

**Closed by juliangut** 2020-10-03 14:25 UTC
