### ISSUE TITLE
 SMPP Session - Not Allow Re-connection 

### ISSUE THREAD

**Issue by mseld** [farhadi/node-smpp#90] opened 2018-12-06 15:22 UTC
I am asking you if you can add new feature to allow session reconnect 
considering is session unbind/closed or even tcp socket closed

**Comment by ritmas** [comment] 2019-01-31 12:50
I would suggest using process control system, like [Supervisor](http://supervisord.org), which will ensure your process / node is up & running. Once socket is unintentionally unbinded/closed, Supervisor restarts it.

**Comment by mseld** [comment] 2019-02-04 12:23
Hello @ritmas  
i'm already use pm2 as process manager 
but i need to keep service a live even connection is dropped and try to establish connection again
because i need to fail over to another after number trails

**Comment by ritmas** [comment] 2019-02-08 11:26
I've tested `pm2` recently, as it was new for me, but I couldn't reproduce the case once connection is dropped from server side and client wouldn't able to reconnect - it always rebind successfully, at least in my case. @mseld could you share exact error code / test scenario which fails client to reconnect/rebind?

My test case: initiated random `session.close();` from server side, but client is keep rebinding:
```js
PM2 > App [client:0] starting in -fork mode-
PM2 > App [client:0] online
client > client: connected
client > client: binded
client > client: socket closed
PM2 > App [client:0] exited with code [0] via signal [SIGINT]
PM2 > App [client:0] starting in -fork mode-
PM2 > App [client:0] online
client > client: connected
client > client: binded
```

**Comment by mseld** [comment] 2019-03-11 21:03
Hello @ritmas there's no problem in pm2 to do like this functionality that you mention in previous comment.
What i need it different , i need to implement fail-over strategy when smpp client can't connect to provider after number of trails it should use different connection.

**Comment by ritmas** [comment] 2019-03-12 10:03
Have you tried the following?
```javascript
var smpp = require('smpp'),
    // used '127.0.0.2' intentionally so to mimic cannot-connect case
    session = smpp.connect('127.0.0.2', 2775);

// info: https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback
session.socket.setTimeout(1000);
session.socket.on('timeout', function() {
    console.log('socket timeout');
    session.destroy();
});
```

**Comment by juliangut** [comment] 2019-05-29 11:07
@mseld it's been more than 2 months from last response, did you find it useful? did you solved your problem?

**Comment by mseld** [comment] 2019-05-29 11:22
@juliangut  Yes i find the way to solve this case using below code

```js
session.socket.on('close', function(had_err) {
    setTimeout(() => {
        session.connect();
        session.resume();
    }, 1000);
});
```

**Comment by juliangut** [comment] 2019-05-29 13:21
Tnaks for the aswer @mseld , closing this issue

**Closed by juliangut** 2019-05-29 13:21 UTC
Labels: feedback-request

**Comment by elhananjair** [comment] 2024-01-12 18:14
@juliangut @mseld Thank you guys for the solution, I was looking for this, 

But I am getting this warning in the terminal: 

`(node:37152) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit`

**Comment by MartianH** [comment] 2024-11-06 11:18
@elhananjair had the same issue using that solution. We had one connection that would send an `ETIMEDOUT` event a solid minute or two after the socket timedout, via the `errror` event:

```json
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"{{ EXTERNAL_HOST }} ","port":8056}
```

In the end, I decided it was better to destroy the underlying TCP socket and recreate the connection. Like so:

```ts
import * as smpp from 'smpp';

class SMPP {

    private readonly sessions: Record<string, Session> = {};
    
    protected createSession(config: Config): Session {
        this.sessions[config.id] = smpp.connect({
          url: config.url,
          auto_enquire_link_period: config.auto_enquire_link_period
        });
        // bind all events to functions here
        this.sessions[identifier].on('close', () => this.on_close(config));
        return this.sessions[config.id];
    }
    
    protected reconnectSession(config: Config): void {
      // important this is called when you know session is closed
      this.sessions[config.id].destroy(() => {
          this.createSession(config);
      });
    }
    
    protected async on_close(config: SmppConfig): Promise<void> {
        // handle closing operations...
        setTimeout(() => this.reconnectSession(config), 10e3);
    }
}
``` 

This seems to work for now.
