### ISSUE TITLE
How should I encode ç when sending an SMS

### ISSUE THREAD

**Issue by phil-warner** [farhadi/node-smpp#105] opened 2019-06-13 12:19 UTC
We are having issues with sending certain Spanish characters to our SMS Gateway. Once we identify that a message has characters outside of the GSM 03.38 alphabet we set the data_coding to 8 and send the message. If any of the following are included the messages appear as far-east asian characters on handsets: ã, ç, á, í.

We have also tried data_coding set to 3, sending a utf16le encoded buffer as the message_payload, and converting the entire message to hex before it is sent.

Can you offer any advice please?

**Comment by ritmas** [comment] 2019-06-13 12:33
Have you tried the default SMSC encoding, allowing SMSC to decide encoding?
```
smpp.consts.ENCODING.SMSC_DEFAULT => 0x00
```

**Comment by phil-warner** [comment] 2019-06-13 20:40
Hi @ritmas. Thanks for the suggestion. I set smpp.consts.ENCODING.SMSC_DEFAULT = 0x00 before I created a new smpp.session. Was that the right approach? I'm still not receiving the ç character but the others were rendered okay.

I couldn't see any documentation on setting smpp.consts.

Thanks again, Phil

**Comment by ritmas** [comment] 2019-06-14 04:16
No, I meant using lib constant `smpp.consts.ENCODING.SMSC_DEFAULT`, not setting it up - it's already defined. Or you can just use hardcoded value `0x00` or `0` for `data_coding`.

**Comment by juliangut** [comment] 2019-08-23 10:10
@phil-warner did you try ritmas' solution? did it worked?

**Comment by juliangut** [comment] 2019-11-11 13:05
@phil-warner could you please give some feedback? the issue is 5 months old with no response from your side

**Comment by juliangut** [comment] 2020-02-13 12:37
I'm closing this issue as not receiving feedback from months, reopen if needed

**Closed by juliangut** 2020-02-13 12:37 UTC
Labels: feedback requested, support
